[package]
name = "scale-encode"
version = "0.1.0"
edition = "2021"

[dependencies]

scale-info = { version = "2.3.0", features = ["bit-vec"] }
thiserror = "1.0.37"
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive", "full"] }
